### ISSUE TITLE
Basic example 

### ISSUE THREAD

**Issue by gedw99** [bloeys/nmage#1]
Is there a basic example yet ?

**Comment by bloeys** [comment]
Hey @gedw99,

It is very early in development so you can't use it to build games yet, but following the Readme and running with `go run .` should currently open a window that shows a 3D object and basic movement with the WASD keys.

I'll make sure to update instructions as we develop the engine more fully :)

**Comment by gedw99** [comment]
Could not build.  I am on an intel mac

can you remember the incarnations for pkg-config ?


````

go build .
# pkg-config --cflags  -- sdl2
pkg-config: exec: "pkg-config": executable file not found in $PATH
# github.com/inkyblackness/imgui-go/v4
warning: unknown warning option '-Wno-subobject-linkage' [-Wunknown-warning-option]


````

**Comment by gedw99** [comment]
I got it almost working. Not sure if your on a mac or what... 

here is my make file:

````
NMAGE_LIB_NAME=nmage
ASS_LIB_NAME=assimp-go
print:

dep:
	git clone https://github.com/bloeys/nmage
	git clone https://github.com/bloeys/assimp-go
	
dep-delete:
	rm -rf $(NMAGE_LIB_NAME) 
	rm -rf $(ASS_LIB_NAME)
dep-os:
# for Mac
	from: https://github.com/veandco/go-sdl2#requirements
	brew install sdl2{,_image,_mixer,_ttf,_gfx} pkg-config
# For Windows ?

# MAC path is
export PKG_CONFIG_PATH=/usr/local/lib/pkgconfig

# WINDOWS is ?
pkg-print:
	ls -al $(PKG_CONFIG_PATH)

	# check that brew works and that sdl2 is there.
	pkg-config --libs sdl2

nmage-build:
	cd $(NMAGE_LIB_NAME) && go build .
nmage-run:
	cd $(NMAGE_LIB_NAME) && ./$(NMAGE_LIB_NAME)

data-list:
	cd test-data && ls -al


````

**Comment by gedw99** [comment]
Thanks for the info . 

It’s a really cool project .

Could you modify my make file and put it in the repo so devs can see how to bootstrap and run . even if it’s not fully working yet .

yeah I just wanted to try assimp. Want to try to get 3d cad models converted from sketch up and view them .

**Comment by gedw99** [comment]
Sketchup supports das / collada

**Comment by gedw99** [comment]
I don’t have a M1 Mac here so can’t try that . But if you get it working then I can try using the makefile on Mac intel.

**Comment by bloeys** [comment]
Good news!
I managed to make it work on my M1 mac, and I think it should work on Intel as well.

Turns out Apple only supports OpenGL up to 4.1, so I changed the code to support 4.1 (was 4.6 previously), and I also found an init bug that didn't affect anything on windows but broke Mac.

The changes and fixes are pushed to the 'mac' branch, so you should be able to clone that and run normally hopefully. If this works we can update the readme and I'll apply the changes  to the main branch on the next stream.

**Comment by gedw99** [comment]
Sweet ! 

Will try it on my Intel max tomorrow and let you know .

**Comment by bloeys** [comment]
Just to update you, all changes are merged to dev!
If you get to test on your mac please do share :D

**Comment by gedw99** [comment]
Hey @bloeys 

No dice on my end:

makefile:
``` 
# https://github.com/bloeys/nmage



NMAGE_LIB_NAME=nmage
ASS_LIB_NAME=assimp-go

BIN_FSPATH=$(PWD)/bin
BIN_NAME=nmage
BIN=$(BIN_FSPATH)/$(BIN_NAME)

all: dep dep-os pkg-print nmage-buildrun
	

print:

dep: dep-delete
	git clone https://github.com/bloeys/nmage -b dev
	git clone https://github.com/bloeys/assimp-go
	
dep-delete:
	rm -rf $(NMAGE_LIB_NAME) 
	rm -rf $(ASS_LIB_NAME)

dep-os:
# for Mac
	#from: https://github.com/veandco/go-sdl2#requirements
	brew install sdl2{,_image,_mixer,_ttf,_gfx} pkg-config
# For Windows ?

# MAC path is
export PKG_CONFIG_PATH=/usr/local/lib/pkgconfig

# WINDOWS is ?
pkg-print:
	ls -al $(PKG_CONFIG_PATH)

	# check that brew works and that sdl2 is there.
	pkg-config --libs sdl2

nmage-build:
	cd $(NMAGE_LIB_NAME) && go build -o $(BIN) .

	cp -rf $(NMAGE_LIB_NAME)/res $(BIN_FSPATH)/res

nmage-buildrun: nmage-build
	cd $(BIN_FSPATH) && ./$(BIN_NAME)
	
nmage-run:
	cd $(NMAGE_LIB_NAME) && go run .

data-list:
	cd test-data && ls -al

``` 

make all:

``` 
make all
rm -rf nmage 
rm -rf assimp-go
git clone https://github.com/bloeys/nmage -b dev
Cloning into 'nmage'...
remote: Enumerating objects: 184, done.
remote: Counting objects: 100% (184/184), done.
remote: Compressing objects: 100% (122/122), done.
remote: Total 184 (delta 71), reused 150 (delta 43), pack-reused 0
Receiving objects: 100% (184/184), 38.28 KiB | 852.00 KiB/s, done.
Resolving deltas: 100% (71/71), done.
git clone https://github.com/bloeys/assimp-go
Cloning into 'assimp-go'...
remote: Enumerating objects: 234, done.
remote: Counting objects: 100% (234/234), done.
remote: Compressing objects: 100% (156/156), done.
remote: Total 234 (delta 110), reused 192 (delta 73), pack-reused 0
Receiving objects: 100% (234/234), 7.38 MiB | 3.03 MiB/s, done.
Resolving deltas: 100% (110/110), done.
#from: https://github.com/veandco/go-sdl2#requirements
brew install sdl2{,_image,_mixer,_ttf,_gfx} pkg-config
Warning: sdl2 2.0.16 is already installed and up-to-date.
To reinstall 2.0.16, run:
  brew reinstall sdl2
Warning: sdl2_image 2.0.5 is already installed and up-to-date.
To reinstall 2.0.5, run:
  brew reinstall sdl2_image
Warning: sdl2_mixer 2.0.4_2 is already installed and up-to-date.
To reinstall 2.0.4_2, run:
  brew reinstall sdl2_mixer
Warning: sdl2_ttf 2.0.15 is already installed and up-to-date.
To reinstall 2.0.15, run:
  brew reinstall sdl2_ttf
Warning: sdl2_gfx 1.0.4 is already installed and up-to-date.
To reinstall 1.0.4, run:
  brew reinstall sdl2_gfx
Warning: pkg-config 0.29.2_3 is already installed and up-to-date.
To reinstall 0.29.2_3, run:
  brew reinstall pkg-config
ls -al /usr/local/lib/pkgconfig
total 16
drwxr-xr-x   81 apple  staff   2592 17 Nov 15:45 .
drwxr-xr-x  322 apple  admin  10304 20 Nov 12:25 ..
lrwxr-xr-x    1 apple  staff     53 15 Nov 14:41 SDL2_gfx.pc -> ../../Cellar/sdl2_gfx/1.0.4/lib/pkgconfig/SDL2_gfx.pc
lrwxr-xr-x    1 apple  staff     57 15 Nov 14:40 SDL2_image.pc -> ../../Cellar/sdl2_image/2.0.5/lib/pkgconfig/SDL2_image.pc
lrwxr-xr-x    1 apple  staff     59 15 Nov 14:40 SDL2_mixer.pc -> ../../Cellar/sdl2_mixer/2.0.4_2/lib/pkgconfig/SDL2_mixer.pc
lrwxr-xr-x    1 apple  staff     54 15 Nov 14:41 SDL2_ttf.pc -> ../../Cellar/sdl2_ttf/2.0.15/lib/pkgconfig/SDL2_ttf.pc
lrwxr-xr-x    1 apple  staff     51 17 Nov 10:15 fdk-aac.pc -> ../../Cellar/fdk-aac/2.0.2/lib/pkgconfig/fdk-aac.pc
lrwxr-xr-x    1 apple  staff     47 15 Nov 14:40 flac++.pc -> ../../Cellar/flac/1.3.3/lib/pkgconfig/flac++.pc
lrwxr-xr-x    1 apple  staff     45 15 Nov 14:40 flac.pc -> ../../Cellar/flac/1.3.3/lib/pkgconfig/flac.pc
-rw-r--r--    1 apple  staff    196 23 Aug 11:34 flatbuffers.pc
lrwxr-xr-x    1 apple  staff     55 24 Sep 13:56 freetype2.pc -> ../../Cellar/freetype/2.11.0/lib/pkgconfig/freetype2.pc
lrwxr-xr-x    1 apple  staff     10 24 Oct  2019 fuse.pc -> osxfuse.pc
lrwxr-xr-x    1 apple  staff     45 24 Sep 12:39 gmp.pc -> ../../Cellar/gmp/6.2.1_1/lib/pkgconfig/gmp.pc
lrwxr-xr-x    1 apple  staff     47 24 Sep 12:39 gmpxx.pc -> ../../Cellar/gmp/6.2.1_1/lib/pkgconfig/gmpxx.pc
lrwxr-xr-x    1 apple  staff     69 17 Nov 15:45 groonga-normalizer-mysql.pc -> ../../Cellar/groonga/11.0.9/lib/pkgconfig/groonga-normalizer-mysql.pc
lrwxr-xr-x    1 apple  staff     52 17 Nov 15:45 groonga.pc -> ../../Cellar/groonga/11.0.9/lib/pkgconfig/groonga.pc
lrwxr-xr-x    1 apple  staff     52 24 Sep 13:56 jbig2dec.pc -> ../../Cellar/jbig2dec/0.19/lib/pkgconfig/jbig2dec.pc
lrwxr-xr-x    1 apple  staff     58 10 Nov 12:12 libbrotlicommon.pc -> ../../Cellar/brotli/1.0.9/lib/pkgconfig/libbrotlicommon.pc
lrwxr-xr-x    1 apple  staff     55 10 Nov 12:12 libbrotlidec.pc -> ../../Cellar/brotli/1.0.9/lib/pkgconfig/libbrotlidec.pc
lrwxr-xr-x    1 apple  staff     55 10 Nov 12:12 libbrotlienc.pc -> ../../Cellar/brotli/1.0.9/lib/pkgconfig/libbrotlienc.pc
lrwxr-xr-x    1 apple  staff     52 10 Nov 12:12 libcares.pc -> ../../Cellar/c-ares/1.18.1/lib/pkgconfig/libcares.pc
lrwxr-xr-x    1 apple  staff     53 17 Nov 15:45 libecpg.pc -> ../../Cellar/postgresql/14.1/lib/pkgconfig/libecpg.pc
lrwxr-xr-x    1 apple  staff     60 17 Nov 15:45 libecpg_compat.pc -> ../../Cellar/postgresql/14.1/lib/pkgconfig/libecpg_compat.pc
lrwxr-xr-x    1 apple  staff     48 24 Sep 13:56 libidn.pc -> ../../Cellar/libidn/1.38/lib/pkgconfig/libidn.pc
lrwxr-xr-x    1 apple  staff     51 25 Jul 12:02 libidn2.pc -> ../../Cellar/libidn2/2.3.2/lib/pkgconfig/libidn2.pc
lrwxr-xr-x    1 apple  staff     73 24 Jun 10:29 libimobiledevice-1.0.pc -> ../../Cellar/libimobiledevice/1.3.0/lib/pkgconfig/libimobiledevice-1.0.pc
lrwxr-xr-x    1 apple  staff     45  8 Feb  2021 libjpeg.pc -> ../../Cellar/jpeg/9d/lib/pkgconfig/libjpeg.pc
lrwxr-xr-x    1 apple  staff     46 23 Apr  2021 liblzma.pc -> ../../Cellar/xz/5.2.5/lib/pkgconfig/liblzma.pc
lrwxr-xr-x    1 apple  staff     55 29 Oct 11:20 libmariadb.pc -> ../../Cellar/mariadb/10.6.4/lib/pkgconfig/libmariadb.pc
lrwxr-xr-x    1 apple  staff     59 15 Nov 14:40 libmodplug.pc -> ../../Cellar/libmodplug/0.8.9.0/lib/pkgconfig/libmodplug.pc
lrwxr-xr-x    1 apple  staff     53 15 Nov 14:40 libmpg123.pc -> ../../Cellar/mpg123/1.29.2/lib/pkgconfig/libmpg123.pc
lrwxr-xr-x    1 apple  staff     58 10 Nov 12:12 libnghttp2.pc -> ../../Cellar/libnghttp2/1.46.0/lib/pkgconfig/libnghttp2.pc
lrwxr-xr-x    1 apple  staff     53 15 Nov 14:40 libout123.pc -> ../../Cellar/mpg123/1.29.2/lib/pkgconfig/libout123.pc
lrwxr-xr-x    1 apple  staff     47 29 Oct 10:39 libpcre.pc -> ../../Cellar/pcre/8.45/lib/pkgconfig/libpcre.pc
lrwxr-xr-x    1 apple  staff     49 29 Oct 10:39 libpcre16.pc -> ../../Cellar/pcre/8.45/lib/pkgconfig/libpcre16.pc
lrwxr-xr-x    1 apple  staff     53 31 Oct 12:32 libpcre2-16.pc -> ../../Cellar/pcre2/10.39/lib/pkgconfig/libpcre2-16.pc
lrwxr-xr-x    1 apple  staff     53 31 Oct 12:32 libpcre2-32.pc -> ../../Cellar/pcre2/10.39/lib/pkgconfig/libpcre2-32.pc
lrwxr-xr-x    1 apple  staff     52 31 Oct 12:32 libpcre2-8.pc -> ../../Cellar/pcre2/10.39/lib/pkgconfig/libpcre2-8.pc
lrwxr-xr-x    1 apple  staff     56 31 Oct 12:32 libpcre2-posix.pc -> ../../Cellar/pcre2/10.39/lib/pkgconfig/libpcre2-posix.pc
lrwxr-xr-x    1 apple  staff     49 29 Oct 10:39 libpcre32.pc -> ../../Cellar/pcre/8.45/lib/pkgconfig/libpcre32.pc
lrwxr-xr-x    1 apple  staff     50 29 Oct 10:39 libpcrecpp.pc -> ../../Cellar/pcre/8.45/lib/pkgconfig/libpcrecpp.pc
lrwxr-xr-x    1 apple  staff     52 29 Oct 10:39 libpcreposix.pc -> ../../Cellar/pcre/8.45/lib/pkgconfig/libpcreposix.pc
lrwxr-xr-x    1 apple  staff     56 17 Nov 15:45 libpgtypes.pc -> ../../Cellar/postgresql/14.1/lib/pkgconfig/libpgtypes.pc
lrwxr-xr-x    1 apple  staff     59 24 Jun 10:28 libplist++-2.0.pc -> ../../Cellar/libplist/2.2.0/lib/pkgconfig/libplist++-2.0.pc
lrwxr-xr-x    1 apple  staff     57 24 Jun 10:28 libplist-2.0.pc -> ../../Cellar/libplist/2.2.0/lib/pkgconfig/libplist-2.0.pc
lrwxr-xr-x    1 apple  staff     50  8 Feb  2021 libpng.pc -> ../../Cellar/libpng/1.6.37/lib/pkgconfig/libpng.pc
lrwxr-xr-x    1 apple  staff     52  8 Feb  2021 libpng16.pc -> ../../Cellar/libpng/1.6.37/lib/pkgconfig/libpng16.pc
lrwxr-xr-x    1 apple  staff     51 17 Nov 15:45 libpq.pc -> ../../Cellar/postgresql/14.1/lib/pkgconfig/libpq.pc
lrwxr-xr-x    1 apple  staff     53 15 Nov 14:40 libsyn123.pc -> ../../Cellar/mpg123/1.29.2/lib/pkgconfig/libsyn123.pc
lrwxr-xr-x    1 apple  staff     54 11 Nov 14:20 libtasn1.pc -> ../../Cellar/libtasn1/4.18.0/lib/pkgconfig/libtasn1.pc
lrwxr-xr-x    1 apple  staff     53 27 Apr  2021 libtiff-4.pc -> ../../Cellar/libtiff/4.3.0/lib/pkgconfig/libtiff-4.pc
lrwxr-xr-x    1 apple  staff     54 24 Jun 10:28 libusb-1.0.pc -> ../../Cellar/libusb/1.0.24/lib/pkgconfig/libusb-1.0.pc
lrwxr-xr-x    1 apple  staff     61 24 Jun 10:29 libusbmuxd-2.0.pc -> ../../Cellar/libusbmuxd/2.0.2/lib/pkgconfig/libusbmuxd-2.0.pc
lrwxr-xr-x    1 apple  staff     48 10 Nov 12:12 libuv.pc -> ../../Cellar/libuv/1.42.0/lib/pkgconfig/libuv.pc
lrwxr-xr-x    1 apple  staff     50 15 Nov 14:40 libwebp.pc -> ../../Cellar/webp/1.2.1_1/lib/pkgconfig/libwebp.pc
lrwxr-xr-x    1 apple  staff     57 15 Nov 14:40 libwebpdecoder.pc -> ../../Cellar/webp/1.2.1_1/lib/pkgconfig/libwebpdecoder.pc
lrwxr-xr-x    1 apple  staff     55 15 Nov 14:40 libwebpdemux.pc -> ../../Cellar/webp/1.2.1_1/lib/pkgconfig/libwebpdemux.pc
lrwxr-xr-x    1 apple  staff     53 15 Nov 14:40 libwebpmux.pc -> ../../Cellar/webp/1.2.1_1/lib/pkgconfig/libwebpmux.pc
lrwxr-xr-x    1 apple  staff     51 15 Oct 11:12 libzip.pc -> ../../Cellar/libzip/1.8.0_1/lib/pkgconfig/libzip.pc
lrwxr-xr-x    1 apple  staff     48 15 Oct 11:12 libzstd.pc -> ../../Cellar/zstd/1.5.0/lib/pkgconfig/libzstd.pc
lrwxr-xr-x    1 apple  staff     52 29 Oct 11:20 mariadb.pc -> ../../Cellar/mariadb/10.6.4/lib/pkgconfig/mariadb.pc
lrwxr-xr-x    1 apple  staff     51 29 Oct 10:39 msgpack.pc -> ../../Cellar/msgpack/4.0.0/lib/pkgconfig/msgpack.pc
lrwxr-xr-x    1 apple  staff     46 15 Nov 14:09 ogg.pc -> ../../Cellar/libogg/1.3.5/lib/pkgconfig/ogg.pc
lrwxr-xr-x    1 apple  staff     45 17 Nov 10:15 opus.pc -> ../../Cellar/opus/1.3.1/lib/pkgconfig/opus.pc
-rw-r--r--    1 apple  staff    258  1 Jul  2018 osxfuse.pc
lrwxr-xr-x    1 apple  staff     59  9 Jun 16:20 protobuf-lite.pc -> ../../Cellar/protobuf/3.17.3/lib/pkgconfig/protobuf-lite.pc
lrwxr-xr-x    1 apple  staff     54  9 Jun 16:20 protobuf.pc -> ../../Cellar/protobuf/3.17.3/lib/pkgconfig/protobuf.pc
lrwxr-xr-x    1 apple  staff     63 17 Nov 15:45 python-3.9-embed.pc -> ../../Cellar/python@3.9/3.9.8/lib/pkgconfig/python-3.9-embed.pc
lrwxr-xr-x    1 apple  staff     57 17 Nov 15:45 python-3.9.pc -> ../../Cellar/python@3.9/3.9.8/lib/pkgconfig/python-3.9.pc
lrwxr-xr-x    1 apple  staff     60 17 Nov 15:45 python3-embed.pc -> ../../Cellar/python@3.9/3.9.8/lib/pkgconfig/python3-embed.pc
lrwxr-xr-x    1 apple  staff     54 17 Nov 15:45 python3.pc -> ../../Cellar/python@3.9/3.9.8/lib/pkgconfig/python3.pc
lrwxr-xr-x    1 apple  staff     46 17 Nov 10:16 sdl.pc -> ../../Cellar/sdl/1.2.15_3/lib/pkgconfig/sdl.pc
lrwxr-xr-x    1 apple  staff     46 15 Nov 14:40 sdl2.pc -> ../../Cellar/sdl2/2.0.16/lib/pkgconfig/sdl2.pc
lrwxr-xr-x    1 apple  staff     49 17 Nov 10:16 theora.pc -> ../../Cellar/theora/1.1.1/lib/pkgconfig/theora.pc
lrwxr-xr-x    1 apple  staff     52 17 Nov 10:16 theoradec.pc -> ../../Cellar/theora/1.1.1/lib/pkgconfig/theoradec.pc
lrwxr-xr-x    1 apple  staff     52 17 Nov 10:16 theoraenc.pc -> ../../Cellar/theora/1.1.1/lib/pkgconfig/theoraenc.pc
lrwxr-xr-x    1 apple  staff     52 15 Nov 14:09 vorbis.pc -> ../../Cellar/libvorbis/1.3.7/lib/pkgconfig/vorbis.pc
lrwxr-xr-x    1 apple  staff     55 15 Nov 14:09 vorbisenc.pc -> ../../Cellar/libvorbis/1.3.7/lib/pkgconfig/vorbisenc.pc
lrwxr-xr-x    1 apple  staff     56 15 Nov 14:09 vorbisfile.pc -> ../../Cellar/libvorbis/1.3.7/lib/pkgconfig/vorbisfile.pc
lrwxr-xr-x    1 apple  staff     47 17 Nov 10:15 vpx.pc -> ../../Cellar/libvpx/1.11.0/lib/pkgconfig/vpx.pc
lrwxr-xr-x    1 apple  staff     45 17 Nov 10:16 x264.pc -> ../../Cellar/x264/r3060/lib/pkgconfig/x264.pc
# check that brew works and that sdl2 is there.
pkg-config --libs sdl2
-L/usr/local/lib -lSDL2
cd nmage && go build -o /Users/apple/workspace/go/src/github.com/gedw99/gio-tools/3d/bloeys__nmage/bin/nmage .
# github.com/inkyblackness/imgui-go/v4
warning: unknown warning option '-Wno-subobject-linkage' [-Wunknown-warning-option]
cp -rf nmage/res /Users/apple/workspace/go/src/github.com/gedw99/gio-tools/3d/bloeys__nmage/bin/res
cd /Users/apple/workspace/go/src/github.com/gedw99/gio-tools/3d/bloeys__nmage/bin && ./nmage
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x0]

runtime stack:
runtime.throw({0x41dd0aa, 0xc00014e000})
        /usr/local/opt/go/libexec/src/runtime/panic.go:1198 +0x71
runtime.sigpanic()
        /usr/local/opt/go/libexec/src/runtime/signal_unix.go:719 +0x396
runtime.asmcgocall(0xc000131500, 0x1500000007e51098)
        /usr/local/opt/go/libexec/src/runtime/asm_amd64.s:769 +0x70

goroutine 1 [syscall, locked to thread]:
runtime.cgocall(0x40ca010, 0xc00004ace0)
        /usr/local/opt/go/libexec/src/runtime/cgocall.go:156 +0x5c fp=0xc00004acb8 sp=0xc00004ac80 pc=0x400621c
github.com/go-gl/gl/v4.1-core/gl._Cfunc_glowCreateVertexArrays(0x0, 0x1, 0xc000132050)
        _cgo_gotypes.go:5715 +0x45 fp=0xc00004ace0 sp=0xc00004acb8 pc=0x409b0e5
github.com/go-gl/gl/v4.1-core/gl.CreateVertexArrays(...)
        /Users/apple/workspace/go/pkg/mod/github.com/go-gl/gl@v0.0.0-20211025173605-bda47ffaa784/v4.1-core/gl/package.go:9393
github.com/bloeys/go-sdl-engine/buffers.NewBufferObject()
        /Users/apple/workspace/go/src/github.com/gedw99/gio-tools/3d/bloeys__nmage/nmage/buffers/buffers.go:156 +0x48 fp=0xc00004ad28 sp=0xc00004ace0 pc=0x40b7028
main.loadBuffers()
        /Users/apple/workspace/go/src/github.com/gedw99/gio-tools/3d/bloeys__nmage/nmage/main.go:218 +0x173 fp=0xc00004ae00 sp=0xc00004ad28 pc=0x40c6713
main.main()
        /Users/apple/workspace/go/src/github.com/gedw99/gio-tools/3d/bloeys__nmage/nmage/main.go:77 +0x291 fp=0xc00004af80 sp=0xc00004ae00 pc=0x40c5c51
runtime.main()
        /usr/local/opt/go/libexec/src/runtime/proc.go:255 +0x227 fp=0xc00004afe0 sp=0xc00004af80 pc=0x4036787
runtime.goexit()
        /usr/local/opt/go/libexec/src/runtime/asm_amd64.s:1581 +0x1 fp=0xc00004afe8 sp=0xc00004afe0 pc=0x405fe01
make: *** [nmage-buildrun] Error 2

```

**Comment by gedw99** [comment]
make nmage-run gives same error too. 



``` 
make nmage-run 
cd nmage && go run .
# github.com/inkyblackness/imgui-go/v4
warning: unknown warning option '-Wno-subobject-linkage' [-Wunknown-warning-option]
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x0]

runtime stack:
runtime.throw({0x41dd0aa, 0xc000112000})
        /usr/local/opt/go/libexec/src/runtime/panic.go:1198 +0x71
runtime.sigpanic()
        /usr/local/opt/go/libexec/src/runtime/signal_unix.go:719 +0x396
runtime.asmcgocall(0xc000063c00, 0x3c00000005e528e8)
        /usr/local/opt/go/libexec/src/runtime/asm_amd64.s:769 +0x70

goroutine 1 [syscall, locked to thread]:
runtime.cgocall(0x40ca010, 0xc00004fce0)
        /usr/local/opt/go/libexec/src/runtime/cgocall.go:156 +0x5c fp=0xc00004fcb8 sp=0xc00004fc80 pc=0x400621c
github.com/go-gl/gl/v4.1-core/gl._Cfunc_glowCreateVertexArrays(0x0, 0x1, 0xc000016148)
        _cgo_gotypes.go:5715 +0x45 fp=0xc00004fce0 sp=0xc00004fcb8 pc=0x409b0e5
github.com/go-gl/gl/v4.1-core/gl.CreateVertexArrays(...)
        /Users/apple/workspace/go/pkg/mod/github.com/go-gl/gl@v0.0.0-20211025173605-bda47ffaa784/v4.1-core/gl/package.go:9393
github.com/bloeys/go-sdl-engine/buffers.NewBufferObject()
        /Users/apple/workspace/go/src/github.com/gedw99/gio-tools/3d/bloeys__nmage/nmage/buffers/buffers.go:156 +0x48 fp=0xc00004fd28 sp=0xc00004fce0 pc=0x40b7028
main.loadBuffers()
        /Users/apple/workspace/go/src/github.com/gedw99/gio-tools/3d/bloeys__nmage/nmage/main.go:218 +0x173 fp=0xc00004fe00 sp=0xc00004fd28 pc=0x40c6713
main.main()
        /Users/apple/workspace/go/src/github.com/gedw99/gio-tools/3d/bloeys__nmage/nmage/main.go:77 +0x291 fp=0xc00004ff80 sp=0xc00004fe00 pc=0x40c5c51
runtime.main()
        /usr/local/opt/go/libexec/src/runtime/proc.go:255 +0x227 fp=0xc00004ffe0 sp=0xc00004ff80 pc=0x4036787
runtime.goexit()
        /usr/local/opt/go/libexec/src/runtime/asm_amd64.s:1581 +0x1 fp=0xc00004ffe8 sp=0xc00004ffe0 pc=0x405fe01
exit status 2
make: *** [nmage-run] Error 1
````

**Comment by bloeys** [comment]
Oops! Missed the VAO call in the dev branch. Should work now ;)

**Comment by gedw99** [comment]
Yes it works on Intel Mac now...


![Screenshot 2021-11-22 at 11 06 25](https://user-images.githubusercontent.com/53147028/142842228-6f469c63-5296-49ec-bfe2-c741e6dc48e2.png)
